### ISSUE TITLE
addon takes device out of standby?

### ISSUE THREAD

**Issue by TheGreatHorla** [LordMike/MBW.BlueRiiot2MQTT#74] opened 2022-09-15 10:04 UTC
Is it possible that this addon takes the device out of standby? For the past three days I put my Blue connect go on standby because my pool is now winterready but the next day, the device is back on. I did not have this problem last year but maybe an update caused this?

**Comment by LordMike** [comment] 2022-09-15 10:11
It cannot. To wake the device from the standby/sleep you need to physically shake it iirc.

Mike.
________________________________
From: TheGreatHorla ***@***.***>
Sent: Thursday, September 15, 2022 12:05:10 PM
To: LordMike/MBW.BlueRiiot2MQTT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LordMike/MBW.BlueRiiot2MQTT] addon takes device out of standby? (Issue #74)


Is it possible that this addon takes the device out of standby? For the past three days I put my Blue connect go on standby because my pool is now winterready but the next day, the device is back on. I did not have this problem last year but maybe an update caused this?

**Comment by TheGreatHorla** [comment] 2022-09-15 10:59
I'm living proof that's not correct. It beeps, it displays standby mode in the app and then the next day it is back active in HA and the app displays active. The device sits in a box on a shelf so it's impossible to accidentally turn it on. 

I just turned the addon off in HA en when I get home I will turn the device back in standby and update this post.

**Comment by LordMike** [comment] 2022-09-16 10:04
It is my understanding that the device is physically sleeping and will only respond to shaking, when it is put into standby. On [BR's page on the topic](https://webshop.swimmingpools.be/en/blog/putting-blue-connect-plus-winter-mode), the steps to reactive involve you "shake the Blue Connect vigorously".

To conserve energy, it is normal for sleeping devices to only react to physical input like shaking or button presses. This cannot happen over the air.

Blue Riiot did recently push an update, but if that's the cause, it's still not this tool.

I'm closing this now - as I don't think this scenario is likely. Hope you get it solved though, maybe it's a device defect.. :)

**Closed as completed by LordMike** 2022-09-16 10:04 UTC
